# HTTP Server
[server]
    Address     = ":9000"
    ServerAgent = "example"
    LogPath     = "./logs/server"

# Logger.
[logger]
    Path   = "./logs/app"
    Level  = "all"
    Stdout = true

[nacos]
    AppName = "example"
    Mode    = "dev"
    FileExtension = "toml"
    EnableConfig = true
    EnableDiscovery = true
    AppPort = 9000

[nacos.config]
    TimeoutMs = 5000
    NotLoadCacheAtStart = true
    RotateTime = "1h"
    MaxAge = 3
    LogLevel = "debug"

[nacos.discovery]
    Scheme = "http"
    ContextPath = "/nacos"
    IpAddr = "127.0.0.1"
    Port  = 8848
